version: "3"
services:
  redis:
    image: redis:5-alpine
    restart: on-failure
  koakuma:
    build: .
    restart: on-failure
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      KOAKUMA_TOKEN:
